# docker-compose.yml
services:
  # First FastAPI instance
  web1:
    build: .
    volumes:
      - .:/app
    environment:
      SERVER_ID: SERVER-1
      REDIS_HOST: redis
    networks:
      - webnet
    depends_on:
      - redis
    ports:
      - "8001:8000"

  # Second FastAPI instance
  web2:
    build: .
    volumes:
      - .:/app
    environment:
      SERVER_ID: SERVER-2
      REDIS_HOST: redis
    networks:
      - webnet
    depends_on:
      - redis
    ports:
      - "8002:8000"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - webnet
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
