name: Python CI

on:
  push:
    branches: [ main, continuous-integration, hw8-database, hw9-iterators, hw10-redis, hw11-celery, hw13-aws ]
  pull_request:
    branches: [ main, continuous-integration, hw8-database, hw9-iterators, hw10-redis, hw11-celery, hw13-aws ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install sqlalchemy pytest flake8

    - name: Check Installed Packages
      run: pip freeze

    - name: Run tests
      run: pytest

    - name: Run flake8
      run: flake8 .

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Upload code via SCP
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.EC2_HOST }}            # Your EC2 public IP or DNS
       username: ${{ secrets.EC2_USER }}         # EC2 instance username (e.g., 'ubuntu')
       key: ${{ secrets.EC2_SSH_KEY }}           # Your SSH private key added as a GitHub secret
       source: "./*"                             # Files to copy (this copies everything in the repo)
       target: "/home/ubuntu/"           # Target directory on EC2 instance


    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install -r requirements.txt
          nohup python3 main.py &