name: Python CI

on:
  push:
    branches: [ main, continuous-integration, hw8-database, hw9-iterators ]
  pull_request:
    branches: [ main, continuous-integration, hw8-database, hw9-iterators]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install sqlalchemy
        pip install pytest flake8

    - name: Check Installed Packages
      run: pip freeze

    - name: Run tests
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8 .
