name: Upload Code via SCP

on:
  push:
    branches:
      - main  # You can adjust the branch name as needed

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload code via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}            # Your EC2 public IP or DNS
          username: ${{ secrets.EC2_USER }}         # EC2 instance username (e.g., 'ubuntu')
          key: ${{ secrets.EC2_SSH_KEY }}           # Your SSH private key added as a GitHub secret
          source: "./*"                             # Files to copy (this copies everything in the repo)
          target: "/home/ubuntu/"           # Target directory on EC2 instance
